### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by Albadylic** [fac-17/Plantbase-Me#1]
Our initial questions:

Have you considered eating more plant-based foods? If so, what would motivate you to to do so?

What sort of challenges do you find with trying to move towards a plant-based diet? 

Could you describe a recent craving you had? and how you satisfied it?

Do you struggle to find plantbased alternatives that fulfill your cravings?

How do you go about looking for new recipes?

Are there any particular technologies you find useful when cooking / looking for recipes? 

Can you describe a plant based recipe you've enjoyed?

What sort of interface would you find useful for this app?

**Comment by Albadylic** [comment]
White female, 24, Survey


*What motivated you to become a vegan?*
Forks over Knives - Healthcare - Prevent sickness. Weight prevention

*What craving have you recently had and how did you alleviate it?*
Crave chicken- can't be replaced!!!
quorn chicken nuggets - Have to be careful- labelled with Vegan
Beyond Beef
Tofu - didn't have to substitute

Challenges - Fewer options- Cheese, beef, 

Cauliflower casserole - used mince meat alternatives

*How do you look for new recipes?*
Ask friends

*Do you write recipes*
Yes

*Are there any particular technologies?*
Google -

*What sort of interface would you find useful for this app?*
Ratouille
Input the ingredients and get given options

Young white couple (male and female), 23-27 interview
 *Have you considered eating more plant-based foods? What might motivate you to do so?*
Eats Huel
Motivated by environmental factors, cut down energy costs and recent Amazon fires, land use

*Challenges of plant based food*
Less variety, blander, lack of availability

*How would you satisfy a craving*
Had a craving for Chorizo, ate chorizo since there isn't really an alternative. 

*How do you find new recipes?*
BBC food food or Happy Pear cookbook

*What technologies might you find useful?*
Tags for budget (i.e. cheap, expensive, middle)
Healthy tag, which course it was (starter, main dessert)
Could use filters like on spare room - you can say I only want to see gluten free, cheap, quick recipes

**Comment by Albadylic** [comment]
### Tine user reasearch - Plantbase Me

### User Surveys

#### Rob:

Have you considered eating more plant-based foods? If so, what would motivate you to to do so?

> better taste, higher protein, cheaper
> 
What sort of challenges do you find with trying to move towards a plant-based diet? 

> I am used to eating richt tasting and delicious foods plantbased substitutes of which I can not find easily, cheaply or in the quantites I require 

Could you descibe a recent craving you had? and how you satisfied it?

> wanted suggar/ sweet -> ate honey - maybe alternative would have satisfied but does not taste as good
>  ate laksa - craving heavy tasting rich food 


Do you struggle to find plantbased alternatives that fullfill your cravings?

> yes


How do you go about looking for new recipes?

> i dont

Would you like to learn to make new recipes?

> maybe

Have you written your own recipes?

> made own recipies but not writted down

Are there any particular technologies you find useful when cooking / looking for recipes? 

> observe good food in restaurant and recreate - online recipies are often shit - if they were good they would have a restaurant

Can you describe a plant based recipe you've enjoyed?

> owe burger (deliveroo in south london)

What sort of interface would you find useful for this app?


> an app that gives information that satisfies craving, ideas/recipies that are cheaper, better tasting or more nutritious -> taste is king! -> wants it to be close to original deal 

> wants adds to be - fast loading no adds no batterie drain - no fancy bullshit just actually works -> likes ryan air app cause you can check in online makes life easier
Does not like uber which is clunky and asks for lots of permisions (locations etc login)

---
Christine ideas:

What interfaces app's inspire you / do you find usefull in terms of UX


What animal products do you find particularily hard to substitute

> honey, eggs, butter

**Comment by emaggy** [comment]
Middle-age women (mothers), Finsbury Park
*Have you considered eating more plant-based foods? If so, what would motivate you to to do so?

Women1 - Yes, considered plant based eating - motivated by land use and environmental issues
Women2 - Yes, health reasons

*What sort of challenges do you find with trying to move towards a plant-based diet?

Women1 - Not a fan of meat, although difficulty in getting children to consume plant-based foods\
Women2 - Can eat Quorn, getting family onboard is a concern

*Do you struggle to find plantbased alternatives that fullfill your cravings?*
Struggle with bacon sandwiches craving - tend to use salty/cheesy foods as an alternative

*How do you go about looking for new recipes? Are there any particular technologies you find useful when cooking / looking for recipes? *

Online- BBC GoodFoods, Google


*What sort of interface would you find useful for this app?
*
Features where you type in ingredients you have and recipes are provided for you

**Comment by Coletterbox** [comment]
## User Research - pair of girls that we realised too late were literal children

What would motivate you to eat more plant-based foods?
"Something good, like if they planted trees."

Challenges
"Eat more healthily."

Would vegan alternatives to products e.g. vegan cheese satisfy your cravings?
"Yes."

Can you describe a recent craving you've had?
[Endless giggling.]
"Aubergine."

How did you satisfy it?
[Still giggling.]
"I didn't."

Where do you look for recipes?
"YouTube."

What technologies do you use?
"Google."
"Whatever's at home." [Probably misheard question.]

**Comment by Coletterbox** [comment]
## User Research - same white female, 24

Vegan
Cravings - well-seasoned chicken, chicken salad - no replacement
Turning vegan - rebuild diet from scratch rather than substitute individual items
Avoiding certain types of cancer
Motivation - terrified of getting sick, bad healthcare
Craved home-made, warm food - made food
Fine with idea that substitutes won't taste the same - worth it for health
Doesn't look for recipes
Post-it recipes
Google

**Comment by Albadylic** [comment]
White male, 25

*Have you considered eating more plant-based foods? What motivates you?*
Make an effort to eat less meat/dairy where possible. Aware of environmental factors and of ethical implications.

*What challenges have you found with eating plant-based alternatives?*
Found no cheese that is a worthy alternative. Often tastes quite strange and lacks texture. Sometimes eating plant-based is more expensive. 

*Could you describe a recent food craving and how you satisfied it?*
Craved fried chicken and made fried cauliflower instead. It was similar and really it's the batter which is tastiest :stuck_out_tongue: 

*How do you look for new recipes?*
Youtube, google, BBC Good Food, sometimes cook books

**Comment by Coletterbox** [comment]
## User Research - anonymous person that definitely isn't myself

- vegetarian since twelve years old - would become vegan if I wasn't already malnourished or if I cared more

- not enough iron

- all foods satisfy all cravings if they are filling; I don't have cravings if I'm not hungry anymore

- recent food craving: sparkling water - generally solve by buying sparkling water

- don't generally look for new recipes - maybe Google a dish if I'm not sure how to make it

**Comment by emaggy** [comment]
Very anonymous meateater 🐄

*Have you considered eating more plant-based foods? If so, what would motivate you to to do so?
Have considered...but meat is too good. Rather had plant based foods to meat meals

*What sort of challenges do you find with trying to move towards a plant-based diet?


Less alternatives - 

*Do you struggle to find plantbased alternatives that fullfill your cravings?*
Yes - not many tasty alternatives that meat 
*How do you go about looking for new recipes? Are there any particular technologies you find useful when cooking / looking for recipes? *

Online-Google, Youtube, Gordon Ramsey tv shows

*What sort of interface would you find useful for this app?
*
Colourful, clear and concise app format would be useful. Allow users to filter for different meals based on category

**Comment by emaggy** [comment]
![image](https://user-images.githubusercontent.com/40627253/64127349-28d92f80-cda9-11e9-99c6-f931908147fe.png)

**Comment by emaggy** [comment]
![image](https://user-images.githubusercontent.com/40627253/64127542-072c7800-cdaa-11e9-8fdf-2fcd5fd8f66e.png)

**Comment by emaggy** [comment]
![image](https://user-images.githubusercontent.com/40627253/64127570-25927380-cdaa-11e9-87c4-c3697331bdb8.png)

**Comment by Coletterbox** [comment]
To add to the young couple's user research responses - when the guy mentioned chorizo, he mentioned feeling that it was important to feel like you're free to fold if you really need to. This seems important for avoiding the "all or nothing" mentality that alienates a lot of meat-eaters; it's better for everyone to do something than for some people to do everything that they feel they can, and for this to happen, people need to not be made to feel like their contribution doesn't make a difference.
