### ISSUE TITLE
Really nice code (plus minor feedback about SQL query)

### ISSUE THREAD

**Issue by jackbridger** [fac-17/Plantbase-Me#102]
Despite lack of issues, I did look through your code. It was really nice and I think that you're on to something great :)

The oonly thing I could find was  in: getProductAndRating.js query. 

You use: 

`    
JOIN (
        SELECT product_id, AVG(rating) AS averages
        FROM ratings
        GROUP BY product_id
    ) AS r
`

Maybe the 'r' could be slightly more clearly named

**Comment by samjam48** [comment]
cheers. 

Yes, I was potentially doing a query 5 times more complicated which had a bunch of other things going on and it was too confusing having so much stuff. but ended up cleaning most of it out and should have made that better. but life...
