### ISSUE TITLE
DOM Manipulation (front end javascript) - 4 hours

### ISSUE THREAD

**Issue by emaggy** [fac-17/Plantbase-Me#109]

**Comment by emaggy** [comment]
Select button on first page, link each product(on results page) to it's product page, click the logo links to homepage - HIGH - 4 hours

**Comment by Albadylic** [comment]
Complete as far as it can be before the slider is built. Just now the select button links to all products but the link can be altered to link based on which product is selected (either in hbs or dom.js, whichever seems most appropriate)

**Comment by Albadylic** [comment]
Relates #117
