### ISSUE TITLE
Clean up Public Javascript

### ISSUE THREAD

**Issue by samjam48** [fac-17/Plantbase-Me#201]
- [x] **Create Different Files**
Separate out the public JAvascript into its main functional elements and just call on the correct pages.
This will prevent code from running when it isn't needed. Allow us to remove the wrapping `if` statements. Make it easier to keep the correct code in the correct place and work on it.
(see where to meet public js for separation example https://github.com/fac-17/Where-Should-We-Meet/tree/master/public/js)

- [x] **Refactor Code**
Stick to ES6 conventions. Remove comments. Make code more readable (better naming conventions). Make things more logical (e.g. don't start counting numbers at 4)

**Comment by Coletterbox** [comment]
Re: starting the count at 4, that confused me too, and made things harder, but now that I've finished the fix I was working on, PLEASE don't change it to something else or it'll break. :'(
